package assignment;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ooi De Shen
 */
public class AcceptPaymentForm extends javax.swing.JFrame {
    private Student currentStudent;
    private List<ClassInfo> enrolledSubjects;
    private double totalFee;
    /**
     * Creates new form AcceptPaymentForm
     */
    public AcceptPaymentForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amountPaidField = new javax.swing.JTextField();
        studentIdField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        enrolledSubjectsArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        totalFeeLabel = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();
        searchButton1 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student ID:");

        studentNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentNameLabel.setText(" -");

        jLabel3.setText("Enrolled Subjects:");

        jLabel4.setText("Total Monthly Fee:");

        jLabel5.setText("Amount Paid (RM):");

        amountPaidField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountPaidFieldActionPerformed(evt);
            }
        });

        studentIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdFieldActionPerformed(evt);
            }
        });

        enrolledSubjectsArea.setEditable(false);
        enrolledSubjectsArea.setBackground(new java.awt.Color(255, 255, 255));
        enrolledSubjectsArea.setColumns(20);
        enrolledSubjectsArea.setRows(5);
        jScrollPane1.setViewportView(enrolledSubjectsArea);

        jLabel6.setText("Student Name: ");

        totalFeeLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        totalFeeLabel.setForeground(new java.awt.Color(255, 0, 0));
        totalFeeLabel.setText("RM 0.00");

        acceptButton.setBackground(new java.awt.Color(102, 255, 102));
        acceptButton.setText("Accept Payment");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        searchButton1.setText("Search");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Accept Student Payement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountPaidField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(studentNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalFeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(studentIdField)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton1)))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acceptButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalFeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(amountPaidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(cancelButton))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountPaidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountPaidFieldActionPerformed
        
    }//GEN-LAST:event_amountPaidFieldActionPerformed

    private void studentIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdFieldActionPerformed
        
    }//GEN-LAST:event_studentIdFieldActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        acceptPayment();
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        searchStudent();
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchStudent() {
        String studentId = studentIdField.getText().trim();
        
        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter a student ID!",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Find student
        List<Student> students = FileHandler.readStudents();
        currentStudent = null;
        
        for (Student student : students) {
            if (student.getId().equals(studentId)) {
                currentStudent = student;
                break;
            }
        }
        
        if (currentStudent == null) {
            JOptionPane.showMessageDialog(this,
                "Student not found!",
                "Search Error",
                JOptionPane.ERROR_MESSAGE);
            resetForm();
            return;
        }
        
        // Find enrollment
        List<Enrollment> enrollments = FileHandler.readEnrollments();
        Enrollment studentEnrollment = null;
        
        for (Enrollment enrollment : enrollments) {
            if (enrollment.getStudentId().equals(studentId)) {
                studentEnrollment = enrollment;
                break;
            }
        }
        
        if (studentEnrollment == null) {
            JOptionPane.showMessageDialog(this,
                "No enrollment found for this student!",
                "Search Error",
                JOptionPane.ERROR_MESSAGE);
            resetForm();
            return;
        }
        
        // Get enrolled subjects
        List<ClassInfo> allClasses = FileHandler.readClasses();
        enrolledSubjects = new ArrayList<>();
        List<String> enrolledSubjectIds = new ArrayList<>();
        
        if (studentEnrollment.getSubjectId1() != null && !studentEnrollment.getSubjectId1().isEmpty()) {
            enrolledSubjectIds.add(studentEnrollment.getSubjectId1());
        }
        if (studentEnrollment.getSubjectId2() != null && !studentEnrollment.getSubjectId2().isEmpty()) {
            enrolledSubjectIds.add(studentEnrollment.getSubjectId2());
        }
        if (studentEnrollment.getSubjectId3() != null && !studentEnrollment.getSubjectId3().isEmpty()) {
            enrolledSubjectIds.add(studentEnrollment.getSubjectId3());
        }
        
        // Find subject details and calculate total fee
        totalFee = 0;
        StringBuilder subjectsText = new StringBuilder();
        
        for (String subjectId : enrolledSubjectIds) {
            for (ClassInfo classInfo : allClasses) {
                if (classInfo.getSubjectId().equals(subjectId)) {
                    enrolledSubjects.add(classInfo);
                    totalFee += classInfo.getMonthlyCost();
                    subjectsText.append("• ").append(classInfo.getSubjectName())
                               .append(" - ").append(classInfo.getDay())
                               .append(" ").append(classInfo.getStartTime())
                               .append("-").append(classInfo.getEndTime())
                               .append(" (RM").append(classInfo.getMonthlyCost()).append(")\n");
                    break;
                }
            }
        }
        
        // Update display
        studentNameLabel.setText(currentStudent.getName());
        enrolledSubjectsArea.setText(subjectsText.toString());
        totalFeeLabel.setText("RM " + String.format("%.2f", totalFee));
        amountPaidField.setText("");
        amountPaidField.requestFocus();
    }
    
    private void resetForm() {
        studentNameLabel.setText("-");
        enrolledSubjectsArea.setText("");
        totalFeeLabel.setText("RM 0.00");
        amountPaidField.setText("");
        currentStudent = null;
        enrolledSubjects = null;
        totalFee = 0;
    }
    
    private void acceptPayment() {
        if (currentStudent == null) {
            JOptionPane.showMessageDialog(this,
                "Please search for a student first!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String amountPaidStr = amountPaidField.getText().trim();
        
        if (amountPaidStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter the amount paid!",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double amountPaid;
        try {
            amountPaid = Double.parseDouble(amountPaidStr);
            if (amountPaid <= 0) {
                throw new NumberFormatException("Negative amount");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid amount!",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Generate payment ID and date
        String paymentId = FileHandler.generateNextPaymentId();
        String paymentDate = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());

        // Create payment record
        Payment payment = new Payment(paymentId, currentStudent.getId(), amountPaid, paymentDate);

        if (FileHandler.appendPayment(payment)) {
            // Generate receipt
            generateReceipt(payment);

            JOptionPane.showMessageDialog(this,
                "Payment accepted successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

            resetForm();
        } else {
            JOptionPane.showMessageDialog(this,
                "Error saving payment!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void generateReceipt(Payment payment) {
        String receiptContent = buildReceiptContent(payment);
        
        // Display receipt with print option
        JTextArea receiptArea = new JTextArea(receiptContent);
        receiptArea.setEditable(false);
        receiptArea.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));
        
        JScrollPane scrollPane = new JScrollPane(receiptArea);
        scrollPane.setPreferredSize(new Dimension(400, 500));
        
        // Create custom dialog with print and cancel buttons
        JDialog receiptDialog = new JDialog(this, "Payment Receipt", true);
        receiptDialog.setLayout(new BorderLayout());
        receiptDialog.add(scrollPane, BorderLayout.CENTER);
        
        // Button panel
        JPanel buttonPanel = new JPanel(new FlowLayout());
        JButton printButton = new JButton("Download and Print Receipt");
        JButton closeButton = new JButton("Cancel");
        
        printButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                printReceipt(receiptContent, payment.getPaymentId());
            }
        });
        
        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                receiptDialog.dispose();
            }
        });
        
        buttonPanel.add(printButton);
        buttonPanel.add(closeButton);
        receiptDialog.add(buttonPanel, BorderLayout.SOUTH);
        
        receiptDialog.setSize(450, 600);
        receiptDialog.setLocationRelativeTo(this);
        receiptDialog.setVisible(true);
    }

    private String buildReceiptContent(Payment payment) {
        StringBuilder receipt = new StringBuilder();
        receipt.append("=====================================\n");
        receipt.append("       TUITION CENTRE RECEIPT        \n");
        receipt.append("=====================================\n\n");
        receipt.append("Receipt No: ").append(payment.getPaymentId()).append("\n");
        receipt.append("Date: ").append(payment.getDateOfPayment()).append("\n\n");
        receipt.append("Student ID: ").append(currentStudent.getId()).append("\n");
        receipt.append("Student Name: ").append(currentStudent.getName()).append("\n\n");
        receipt.append("Subjects Covered:\n");
        receipt.append("----------------------------------\n");
        
        for (ClassInfo classInfo : enrolledSubjects) {
            receipt.append("• ").append(classInfo.getSubjectName())
                   .append(" (RM").append(classInfo.getMonthlyCost()).append(")\n");
        }
        
        receipt.append("\n----------------------------------\n");
        receipt.append("Total Monthly Fee: RM ").append(String.format("%.2f", totalFee)).append("\n");
        receipt.append("Amount Paid: RM ").append(String.format("%.2f", payment.getAmountPaid())).append("\n");
        
        if (payment.getAmountPaid() < totalFee) {
            double balance = totalFee - payment.getAmountPaid();
            receipt.append("Balance Due: RM ").append(String.format("%.2f", balance)).append("\n");
        } else if (payment.getAmountPaid() > totalFee) {
            double excess = payment.getAmountPaid() - totalFee;
            receipt.append("Excess Payment: RM ").append(String.format("%.2f", excess)).append("\n");
        }
        
        receipt.append("\n=====================================\n");
        receipt.append("    Thank you for your payment!      \n");
        receipt.append("=====================================\n");
        
        return receipt.toString();
    }
    
    private void downloadReceipt(String receiptContent, String paymentId) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Receipt");
        fileChooser.setSelectedFile(new java.io.File("Receipt_" + paymentId + ".txt"));
        
        // Set file filter to show only text files
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(java.io.File file) {
                return file.isDirectory() || file.getName().toLowerCase().endsWith(".txt");
            }
            
            @Override
            public String getDescription() {
                return "Text Files (*.txt)";
            }
        });
        
        int result = fileChooser.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();
            
            // Ensure the file has .txt extension
            String filePath = selectedFile.getAbsolutePath();
            if (!filePath.toLowerCase().endsWith(".txt")) {
                filePath += ".txt";
                selectedFile = new java.io.File(filePath);
            }
            
            try (java.io.PrintWriter writer = new java.io.PrintWriter(selectedFile)) {
                writer.print(receiptContent);
                JOptionPane.showMessageDialog(this,
                    "Receipt saved successfully to:\n" + selectedFile.getAbsolutePath(),
                    "Download Complete",
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this,
                    "Error saving receipt:\n" + e.getMessage(),
                    "Download Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void downloadPdfReceipt(String receiptContent, String paymentId) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save PDF Receipt");
        fileChooser.setSelectedFile(new java.io.File("Receipt_" + paymentId + ".pdf"));
        
        // Set file filter to show only PDF files
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(java.io.File file) {
                return file.isDirectory() || file.getName().toLowerCase().endsWith(".pdf");
            }
            
            @Override
            public String getDescription() {
                return "PDF Files (*.pdf)";
            }
        });
        
        int result = fileChooser.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();
            
            // Ensure the file has .pdf extension
            String filePath = selectedFile.getAbsolutePath();
            if (!filePath.toLowerCase().endsWith(".pdf")) {
                filePath += ".pdf";
                selectedFile = new java.io.File(filePath);
            }
            
            try {
                generatePdfFile(receiptContent, selectedFile);
                JOptionPane.showMessageDialog(this,
                    "PDF Receipt saved successfully to:\n" + selectedFile.getAbsolutePath(),
                    "Download Complete",
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error saving PDF receipt:\n" + e.getMessage(),
                    "Download Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void generatePdfFile(String receiptContent, java.io.File outputFile) throws Exception {
        // Create a simple PDF using Java's built-in capabilities
        // This is a basic implementation - for a more professional PDF, you'd need iText or similar library
        
        try (java.io.PrintWriter writer = new java.io.PrintWriter(outputFile)) {
            // Write a simple text-based PDF structure
            // Note: This is a very basic approach. For proper PDF generation, you'd need a library like iText
            writer.println("%PDF-1.4");
            writer.println("1 0 obj");
            writer.println("<<");
            writer.println("/Type /Catalog");
            writer.println("/Pages 2 0 R");
            writer.println(">>");
            writer.println("endobj");
            
            // For now, we'll create a text file with .pdf extension
            // In a real implementation, you'd use iText or similar library
            writer.println("PDF Receipt Content:");
            writer.println(receiptContent);
        }
        
        // Show a message that this is a simplified PDF
        JOptionPane.showMessageDialog(this,
            "Note: This is a simplified PDF format.\nFor professional PDF generation, please install iText library.",
            "PDF Generation",
            JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void printReceipt(String receiptContent, String paymentId) {
        try {
            // Create a printable object
            Printable printable = new Printable() {
                @Override
                public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                    if (pageIndex > 0) {
                        return NO_SUCH_PAGE;
                    }
                    
                    Graphics2D g2d = (Graphics2D) graphics;
                    g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                    
                    // Set font and color
                    g2d.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 10));
                    g2d.setColor(java.awt.Color.BLACK);
                    
                    // Split content into lines
                    String[] lines = receiptContent.split("\n");
                    int y = 20;
                    int lineHeight = 15;
                    
                    for (String line : lines) {
                        if (y > pageFormat.getImageableHeight() - 50) {
                            break; // Don't print beyond page
                        }
                        g2d.drawString(line, 20, y);
                        y += lineHeight;
                    }
                    
                    return PAGE_EXISTS;
                }
            };
            
            // Create print job
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(printable);
            
            if (job.printDialog()) {
                job.print();
                JOptionPane.showMessageDialog(this,
                    "Receipt printed successfully!",
                    "Print Complete",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(this,
                "Error printing receipt:\n" + e.getMessage(),
                "Print Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
        
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceptPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceptPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceptPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceptPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceptPaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JTextField amountPaidField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea enrolledSubjectsArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JLabel totalFeeLabel;
    // End of variables declaration//GEN-END:variables
}
