package assignment;

import java.io.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;

public class AddEditReceptionist extends javax.swing.JFrame {

    public AddEditReceptionist() {
        initComponents();
        javax.swing.event.DocumentListener docListener = new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { checkFields(addNew); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { checkFields(addNew); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { checkFields(addNew); }
        };
        edit_name.getDocument().addDocumentListener(docListener);
        edit_pass.getDocument().addDocumentListener(docListener);
        edit_mail.getDocument().addDocumentListener(docListener);
        edit_num.getDocument().addDocumentListener(docListener);
        setDefaultCloseOperation(AddEditTutor.DISPOSE_ON_CLOSE);
        String [] colHeading = {"Receptionist ID","Username","Password","Email","Phone Number"};
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnIdentifiers(colHeading);

        File file = new File("receptionists.txt");

        try {
            BufferedReader br = new BufferedReader(new FileReader("receptionists.txt"));
            String line;

            while ((line = br.readLine()) != null) {
                String[] data = line.split("::");  
                if (data.length == 5) {           
                    String userID = data[0].trim();
                    String username = data[2].trim();
                    String password = data[1].trim();
                    String email = data[3].trim();
                    String phone_number = data[4].trim();

                    model.addRow(new Object[]{userID, username, password, email, phone_number});
                }
            }

          br.close();
     } catch (IOException e) {
          e.printStackTrace();
       }
       save.setEnabled(false);
       delete.setEnabled(false);
       addNew.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        recep_back = new javax.swing.JButton();
        edit_num = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edit_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        edit_pass = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edit_mail = new javax.swing.JTextField();
        addNew = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Table of Registered Receptionist");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Receptionist Management ");

        recep_back.setBackground(java.awt.Color.red);
        recep_back.setForeground(java.awt.Color.black);
        recep_back.setText("Back");
        recep_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recep_backActionPerformed(evt);
            }
        });

        edit_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_numActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Password");

        edit_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_nameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Username");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Email");

        edit_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_passActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Phone Number");

        addNew.setText("Add New");
        addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(addNew)
                .addGap(48, 48, 48)
                .addComponent(delete)
                .addGap(50, 50, 50)
                .addComponent(save)
                .addGap(50, 50, 50)
                .addComponent(recep_back)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edit_num, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(edit_mail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edit_pass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edit_name, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(save)
                        .addComponent(recep_back))
                    .addComponent(delete)
                    .addComponent(addNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recep_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recep_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_recep_backActionPerformed

    private void edit_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_numActionPerformed

    private void edit_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_passActionPerformed

    private void addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewActionPerformed
        txtManagementFunctions run = new txtManagementFunctions();
        List<String[]> data = run.openTxtFile("receptionists.txt");
        String newID = run.generateID(data, "RP");
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String [] dataRow = {newID,edit_name.getText(),edit_pass.getText(),edit_mail.getText(),edit_num.getText()};
        model.addRow(dataRow);
        String [] txtDataRow = {newID,edit_pass.getText(),edit_name.getText(),edit_mail.getText(),edit_num.getText()};
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("receptionists.txt", true))) {
            writer.write(String.join("::", txtDataRow));
            writer.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addNewActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow >= 0) {
            // Get the ID
            String targetID = model.getValueAt(selectedRow, 0).toString();

            // Call your existing method to remove from file
            txtManagementFunctions run = new txtManagementFunctions();
            run.deleteID(targetID, "receptionists.txt");

            // Remove the row from the table model
            model.removeRow(selectedRow);
        
            // Clear the text fields
            edit_name.setText("");
            edit_pass.setText("");
            edit_mail.setText("");
            edit_num.setText("");

            // Disable buttons if needed
            save.setEnabled(false);
            delete.setEnabled(false);

            System.out.println("Deleted receptionist ID: " + targetID);
        } else {
            System.out.println("No row selected.");
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        if (selectedRowIndex >= 0) {
           
            String username = edit_name.getText().trim();
            String password = edit_pass.getText().trim();
            String email = edit_mail.getText().trim();
            String phone = edit_num.getText().trim();

            model.setValueAt(username, selectedRowIndex, 1);
            model.setValueAt(password, selectedRowIndex, 2);
            model.setValueAt(email, selectedRowIndex, 3);
            model.setValueAt(phone, selectedRowIndex, 4);

            try (BufferedWriter bw = new BufferedWriter(new FileWriter("receptionists.txt", false))) {
                for (int i = 0; i < model.getRowCount(); i++) {
                    String id = model.getValueAt(i, 0).toString();
                    String uname = model.getValueAt(i, 1).toString();
                    String pass = model.getValueAt(i, 2).toString();
                    String mail = model.getValueAt(i, 3).toString();
                    String num = model.getValueAt(i, 4).toString();
                    String line = String.join("::", id, uname, pass, mail, num);
                    bw.write(line);
                    bw.newLine();
                }
                System.out.println("File updated successfully.");
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("No row selected to save.");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void edit_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_nameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();

        if (selectedRowIndex >= 0) {
            edit_name.setText(model.getValueAt(selectedRowIndex, 1).toString());
            edit_pass.setText(model.getValueAt(selectedRowIndex, 2).toString());
            edit_mail.setText(model.getValueAt(selectedRowIndex, 3).toString());
            edit_num.setText(model.getValueAt(selectedRowIndex, 4).toString());

            delete.setEnabled(true);
            save.setEnabled(true);     
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void checkFields(javax.swing.JButton button) {
        boolean allFilled = !edit_name.getText().trim().isEmpty()
            && !edit_pass.getText().trim().isEmpty()
            && !edit_mail.getText().trim().isEmpty()
            && !edit_num.getText().trim().isEmpty();
            button.setEnabled(allFilled);
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditReceptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNew;
    private javax.swing.JButton delete;
    private javax.swing.JTextField edit_mail;
    private javax.swing.JTextField edit_name;
    private javax.swing.JTextField edit_num;
    private javax.swing.JTextField edit_pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton recep_back;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
