package assignment;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.List;

public class AdminProfile extends javax.swing.JFrame {

    private String username;
    private String password;
    private String email;
    private String phone_number;
    private String ID;
    
    public AdminProfile(String username,String password,String email,String phone_number,String ID) {
        initComponents();
        setDefaultCloseOperation(AddEditTutor.DISPOSE_ON_CLOSE);
        this.password = password;
        this.username = username;
        this.email = email;
        this.phone_number = phone_number;
        this.ID = ID;
        profile_pass.setText(password);
        profile_name.setText(username);
        profile_email.setText(email);
        profile_number.setText(phone_number);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        profile_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        profile_pass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        profile_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        profile_number = new javax.swing.JTextField();
        profile_exit = new javax.swing.JButton();
        save_profile = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Name");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Profile");

        profile_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Password");

        profile_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_passActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Email");

        profile_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_emailActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Phone Number");

        profile_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_numberActionPerformed(evt);
            }
        });

        profile_exit.setBackground(java.awt.Color.red);
        profile_exit.setForeground(java.awt.Color.black);
        profile_exit.setText("Back");
        profile_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_exitActionPerformed(evt);
            }
        });

        save_profile.setBackground(java.awt.Color.green);
        save_profile.setForeground(java.awt.Color.black);
        save_profile.setText("Save");
        save_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_profileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profile_name)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(save_profile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(profile_exit)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_pass)
                    .addComponent(profile_email)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(profile_number))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profile_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profile_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profile_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(profile_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile_exit)
                    .addComponent(save_profile))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profile_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_nameActionPerformed
        
    }//GEN-LAST:event_profile_nameActionPerformed

    private void save_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_profileActionPerformed
        String newName = profile_name.getText().trim();
        String newPass = profile_pass.getText().trim();
        String newEmail = profile_email.getText().trim();
        String newPhone = profile_number.getText().trim();
        String filePath = "admins.txt";



        List<String[]> lines = txtManagementFunctions.openTxtFile(filePath);
        boolean updated = false;

        try (BufferedWriter bw = new BufferedWriter(new FileWriter(filePath))) {
            for (String[] line : lines) {
                if (line.length > 0 && line[0].equals(ID)) {
                    String updatedLine = ID + "::" + newPass + "::" + newName + "::" + newEmail + "::" + newPhone;
                    bw.write(updatedLine);
                    updated = true;
                } else {
                    bw.write(String.join("::", line));
                }
                bw.newLine();
            }
            if (updated) {
                javax.swing.JOptionPane.showMessageDialog(this, "Profile updated successfully!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "ID not found.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_save_profileActionPerformed

    private void profile_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_profile_exitActionPerformed

    private void profile_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile_emailActionPerformed

    private void profile_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profile_numberActionPerformed

    private void profile_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_passActionPerformed

    }//GEN-LAST:event_profile_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfile("Guest","Guest","Guest","Guest","Guest").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField profile_email;
    private javax.swing.JButton profile_exit;
    private javax.swing.JTextField profile_name;
    private javax.swing.JTextField profile_number;
    private javax.swing.JTextField profile_pass;
    private javax.swing.JButton save_profile;
    // End of variables declaration//GEN-END:variables
}
