package assignment;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ooi De Shen
 */
public class DeleteStudentForm extends javax.swing.JFrame {
    private Student currentStudent;

    /**
     * Creates new form DeleteStudentForm
     */
    public DeleteStudentForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentDetailsArea = new javax.swing.JTextArea();
        deleteButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Delete Student Record");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Warning: This action will permanently delete the student and their enrollment records!");

        jLabel4.setText("Student ID:");

        studentIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Student Details:");

        studentDetailsArea.setEditable(false);
        studentDetailsArea.setColumns(20);
        studentDetailsArea.setRows(5);
        jScrollPane1.setViewportView(studentDetailsArea);

        deleteButton.setBackground(new java.awt.Color(102, 255, 102));
        deleteButton.setText("Delete Student");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(658, 658, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(studentIdField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton))
                            .addComponent(jScrollPane1))
                        .addGap(47, 47, 47))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(deleteButton)
                .addGap(28, 28, 28)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(cancelButton))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdFieldActionPerformed
        
    }//GEN-LAST:event_studentIdFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchStudent();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteStudent();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchStudent() {
        String studentId = studentIdField.getText().trim();
        
        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter a student ID!",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Find student
        List<Student> students = FileHandler.readStudents();
        currentStudent = null;
        
        for (Student student : students) {
            if (student.getId().equals(studentId)) {
                currentStudent = student;
                break;
            }
        }
        
        if (currentStudent == null) {
            JOptionPane.showMessageDialog(this,
                "Student not found!",
                "Search Error",
                JOptionPane.ERROR_MESSAGE);
            resetForm();
            return;
        }
        
        // Display student details
        StringBuilder details = new StringBuilder();
        details.append("Student ID: ").append(currentStudent.getId()).append("\n");
        details.append("Name: ").append(currentStudent.getName()).append("\n");
        details.append("IC/Passport: ").append(currentStudent.getIc()).append("\n");
        details.append("Email: ").append(currentStudent.getEmail()).append("\n");
        details.append("Phone: ").append(currentStudent.getPhone()).append("\n");
        details.append("Address: ").append(currentStudent.getAddress()).append("\n");
        details.append("Level: ").append(currentStudent.getLevel()).append("\n\n");
        
        // Find and display enrollment
        List<Enrollment> enrollments = FileHandler.readEnrollments();
        List<ClassInfo> classes = FileHandler.readClasses();
        
        for (Enrollment enrollment : enrollments) {
            if (enrollment.getStudentId().equals(studentId)) {
                details.append("Enrolled Subjects:\n");
                details.append("------------------\n");
                
                List<String> subjectIds = new ArrayList<>();
                if (enrollment.getSubjectId1() != null && !enrollment.getSubjectId1().isEmpty()) {
                    subjectIds.add(enrollment.getSubjectId1());
                }
                if (enrollment.getSubjectId2() != null && !enrollment.getSubjectId2().isEmpty()) {
                    subjectIds.add(enrollment.getSubjectId2());
                }
                if (enrollment.getSubjectId3() != null && !enrollment.getSubjectId3().isEmpty()) {
                    subjectIds.add(enrollment.getSubjectId3());
                }
                
                for (String subjectId : subjectIds) {
                    for (ClassInfo classInfo : classes) {
                        if (classInfo.getSubjectId().equals(subjectId)) {
                            details.append("• ").append(classInfo.getSubjectName())
                                   .append(" (").append(classInfo.getDay()).append(" ")
                                   .append(classInfo.getStartTime()).append("-")
                                   .append(classInfo.getEndTime()).append(")\n");
                            break;
                        }
                    }
                }
                
                if (subjectIds.isEmpty()) {
                    details.append("No subjects enrolled\n");
                }
                break;
            }
        }
        
        studentDetailsArea.setText(details.toString());
        deleteButton.setEnabled(true);
    }
    
    private void resetForm() {
        studentDetailsArea.setText("");
        deleteButton.setEnabled(false);
        currentStudent = null;
    }
    
    private void deleteStudent() {
        if (currentStudent == null) {
            return;
        }
        
        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this student?\n\n" +
            "Student: " + currentStudent.getName() + " (" + currentStudent.getId() + ")\n\n" +
            "This action cannot be undone!",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Delete from student.txt
        List<Student> students = FileHandler.readStudents();
        List<Student> updatedStudents = new ArrayList<>();
        
        for (Student student : students) {
            if (!student.getId().equals(currentStudent.getId())) {
                updatedStudents.add(student);
            }
        }
        
        // Delete from enrollment.txt
        List<Enrollment> enrollments = FileHandler.readEnrollments();
        List<Enrollment> updatedEnrollments = new ArrayList<>();
        
        for (Enrollment enrollment : enrollments) {
            if (!enrollment.getStudentId().equals(currentStudent.getId())) {
                updatedEnrollments.add(enrollment);
            }
        }
        
        // Save updated files
        boolean studentDeleted = FileHandler.updateStudents(updatedStudents);
        boolean enrollmentDeleted = FileHandler.updateEnrollments(updatedEnrollments);
        
        if (studentDeleted && enrollmentDeleted) {
            JOptionPane.showMessageDialog(this,
                "Student record deleted successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Clear form
            studentIdField.setText("");
            resetForm();
        } else {
            JOptionPane.showMessageDialog(this,
                "Error deleting student record!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextArea studentDetailsArea;
    private javax.swing.JTextField studentIdField;
    // End of variables declaration//GEN-END:variables
}
