package assignment;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ooi De Shen
 */
public class UpdateEnrollmentForm extends javax.swing.JFrame {
    private List<JCheckBox> subjectCheckBoxes;
    private List<ClassInfo> classes;
    private Student currentStudent;
    private Enrollment currentEnrollment;

    /**
     * Creates new form UpdateEnrollmentFormBackUp
     */
    public UpdateEnrollmentForm() {
        initComponents();
        setLocationRelativeTo(null);
        // Load subjects (replace with your actual subject loading logic)
        classes = FileHandler.readClasses();
        subjectCheckBoxes = new ArrayList<>();
        subjectPanel.setLayout(new java.awt.GridLayout(5, 2)); // 5 rows, 2 columns

        for (ClassInfo classInfo : classes) {
            JCheckBox checkBox = new JCheckBox(classInfo.getSubjectName() + " - " + classInfo.getDay() + " " + classInfo.getStartTime() + "-" + classInfo.getEndTime());
            checkBox.setActionCommand(classInfo.getSubjectId());
            subjectCheckBoxes.add(checkBox);
            subjectPanel.add(checkBox);
            checkBox.setEnabled(false); // Disabled until a student is found
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentNameLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subjectPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        currentEnrollmentLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentNameLabel.setText(" -");

        jLabel7.setText("Current Enrollment:");

        jLabel8.setText("Update Subject Selection (Maximum 3):");

        subjectPanel.setBackground(new java.awt.Color(255, 255, 255));
        subjectPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout subjectPanelLayout = new javax.swing.GroupLayout(subjectPanel);
        subjectPanel.setLayout(subjectPanelLayout);
        subjectPanelLayout.setHorizontalGroup(
            subjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        subjectPanelLayout.setVerticalGroup(
            subjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        updateButton.setBackground(new java.awt.Color(102, 255, 102));
        updateButton.setText("Update Enrollment");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Update Student Enrollment");

        jLabel4.setText("Student ID:");

        studentIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Student Name: ");

        currentEnrollmentLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        currentEnrollmentLabel.setText(" -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(subjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(currentEnrollmentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(studentNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(currentEnrollmentLabel))
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(cancelButton))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateEnrollment();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void studentIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdFieldActionPerformed
        
    }//GEN-LAST:event_studentIdFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        searchStudent();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchStudent() {
        String studentId = studentIdField.getText().trim();
        
        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter a student ID!",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Find student
        List<Student> students = FileHandler.readStudents();
        currentStudent = null;
        
        for (Student student : students) {
            if (student.getId().equals(studentId)) {
                currentStudent = student;
                break;
            }
        }
        
        if (currentStudent == null) {
            JOptionPane.showMessageDialog(this,
                "Student not found!",
                "Search Error",
                JOptionPane.ERROR_MESSAGE);
            resetForm();
            return;
        }
        
        // Find enrollment
        List<Enrollment> enrollments = FileHandler.readEnrollments();
        currentEnrollment = null;
        
        for (Enrollment enrollment : enrollments) {
            if (enrollment.getStudentId().equals(studentId)) {
                currentEnrollment = enrollment;
                break;
            }
        }
        
        // Update display
        studentNameLabel.setText(currentStudent.getName());
        
        // Display current enrollment
        if (currentEnrollment != null) {
            StringBuilder enrollmentText = new StringBuilder("<html>");
            List<String> enrolledSubjectIds = new ArrayList<>();
            
            if (currentEnrollment.getSubjectId1() != null && !currentEnrollment.getSubjectId1().isEmpty()) {
                enrolledSubjectIds.add(currentEnrollment.getSubjectId1());
            }
            if (currentEnrollment.getSubjectId2() != null && !currentEnrollment.getSubjectId2().isEmpty()) {
                enrolledSubjectIds.add(currentEnrollment.getSubjectId2());
            }
            if (currentEnrollment.getSubjectId3() != null && !currentEnrollment.getSubjectId3().isEmpty()) {
                enrolledSubjectIds.add(currentEnrollment.getSubjectId3());
            }
            
            for (String subjectId : enrolledSubjectIds) {
                List<ClassInfo> classes = FileHandler.readClasses();
                for (ClassInfo classInfo : classes) {
                    if (classInfo.getSubjectId().equals(subjectId)) {
                        enrollmentText.append("• ").append(classInfo.getSubjectName())
                                     .append(" (").append(classInfo.getDay()).append(" ")
                                     .append(classInfo.getStartTime()).append("-")
                                     .append(classInfo.getEndTime()).append(")<br>");
                        break;
                    }
                }
            }
            
            if (enrolledSubjectIds.isEmpty()) {
                enrollmentText.append("No subjects enrolled");
            }
            
            enrollmentText.append("</html>");
            currentEnrollmentLabel.setText(enrollmentText.toString());
            
            // Update checkboxes
            for (JCheckBox checkBox : subjectCheckBoxes) {
                checkBox.setEnabled(true);
                checkBox.setSelected(enrolledSubjectIds.contains(checkBox.getActionCommand()));
            }
        } else {
            currentEnrollmentLabel.setText("No enrollment found");
            for (JCheckBox checkBox : subjectCheckBoxes) {
                checkBox.setEnabled(true);
                checkBox.setSelected(false);
            }
        }
    }
    
    private void resetForm() {
        studentNameLabel.setText("-");
        currentEnrollmentLabel.setText("-");
        for (JCheckBox checkBox : subjectCheckBoxes) {
            checkBox.setEnabled(false);
            checkBox.setSelected(false);
        }
        currentStudent = null;
        currentEnrollment = null;
    }
    
    private void updateEnrollment() {
        if (currentStudent == null) {
            JOptionPane.showMessageDialog(this,
                "Please search for a student first!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get selected subjects
        List<String> selectedSubjectIds = new ArrayList<>();
        for (JCheckBox checkBox : subjectCheckBoxes) {
            if (checkBox.isSelected()) {
                selectedSubjectIds.add(checkBox.getActionCommand());
            }
        }
        
        if (selectedSubjectIds.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please select at least one subject!",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (selectedSubjectIds.size() > 3) {
            JOptionPane.showMessageDialog(this,
                "You can only select a maximum of 3 subjects!",
                "Input Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Update enrollment
        List<Enrollment> enrollments = FileHandler.readEnrollments();
        boolean found = false;
        
        for (int i = 0; i < enrollments.size(); i++) {
            if (enrollments.get(i).getStudentId().equals(currentStudent.getId())) {
                // Update existing enrollment
                Enrollment updatedEnrollment = new Enrollment(
                    currentStudent.getId(),
                    selectedSubjectIds.size() > 0 ? selectedSubjectIds.get(0) : null,
                    selectedSubjectIds.size() > 1 ? selectedSubjectIds.get(1) : null,
                    selectedSubjectIds.size() > 2 ? selectedSubjectIds.get(2) : null
                );
                enrollments.set(i, updatedEnrollment);
                found = true;
                break;
            }
        }
        
        if (!found) {
            // Create new enrollment if not found
            Enrollment newEnrollment = new Enrollment(
                currentStudent.getId(),
                selectedSubjectIds.size() > 0 ? selectedSubjectIds.get(0) : null,
                selectedSubjectIds.size() > 1 ? selectedSubjectIds.get(1) : null,
                selectedSubjectIds.size() > 2 ? selectedSubjectIds.get(2) : null
            );
            enrollments.add(newEnrollment);
        }
        
        // Save updated enrollments
        if (FileHandler.updateEnrollments(enrollments)) {
            JOptionPane.showMessageDialog(this,
                "Enrollment updated successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                "Error updating enrollment!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEnrollmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEnrollmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEnrollmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEnrollmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEnrollmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentEnrollmentLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JPanel subjectPanel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
